server:
  port: '8080'

spring:
  profiles:
    active: local
  datasource:
    url: 'jdbc:mysql://localhost:3307/student?allowPublicKeyRetrieval=true&useSSL=false'
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      password: 'bar'

logging:
  level:
    root: DEBUG
    com:
      student:
        management: DEBUG

jwt:
  secret: "Jwt Secret"

authentication:
  username: "Vishal"
  password: "123456"